/* EG182 Glossary Data — all terms across all topics */

const glossaryData = {
  t1: {
    name: "Topic 1 — General Manufacturing",
    terms: [
      ["Manufacturing (technological)","Applying physical/chemical processes to change the geometry, properties or appearance of a material to make parts"],
      ["Manufacturing (economic)","Transforming raw materials into items of greater value — adding value at each manufacturing step"],
      ["Processing operation","Transforms a single material — casting, machining, moulding, forging, heat treatment"],
      ["Assembly operation","Joins two or more components together — welding, bolting, adhesive bonding, riveting"],
      ["Consumer goods","Bought by individuals for personal use — cars, phones, tyres, tennis rackets"],
      ["Capital goods","Bought by companies to produce other goods or services — lathes, aircraft, robots, CNC machines"],
      ["Primary industry","Extracts raw materials from nature — agriculture, fishing, mining, forestry, oil drilling"],
      ["Secondary industry","Manufacturing — transforms primary materials into finished products. This module."],
      ["Tertiary industry","Services — restaurants, retail, banking, healthcare, education. No physical product made."],
      ["Production quantity","Units produced per year. Low: 1-100, Medium: 100-10,000, High: 10,000+"],
      ["Production variety","Number of different product types. High variety + high quantity = too expensive. Trade-off."],
      ["Net shape","Part exits process at final dimensions — no further machining needed. Most efficient."],
      ["Near-net shape","Part requires only minimal finishing — most PM and investment casting achieve this"],
      ["Job shop","Low volume, high variety production — custom work, expensive per part"],
      ["Batch production","Medium volume — parts made in batches, tooling changed between batches"],
      ["Mass production","High volume — dedicated equipment, low cost per part, low variety"],
    ]
  },
  t2: {
    name: "Topic 2 — Metal Casting",
    terms: [
      ["Casting","Molten metal poured into a mould cavity and allowed to solidify — produces complex shapes"],
      ["Expendable mould","Destroyed after each casting — sand, ceramic shell, polystyrene foam. New mould per part."],
      ["Permanent mould","Reused thousands of times — made from metal. Die casting, centrifugal casting."],
      ["Pattern","Full-sized replica of desired part used to form the mould cavity — wood, metal, or plastic"],
      ["Draft angle","Taper on pattern walls allowing clean withdrawal without collapsing the mould cavity"],
      ["Shrinkage allowance","Pattern made oversized — accounts for metal contracting during solidification"],
      ["Machining allowance","Extra material left on casting for subsequent machining to precise final dimensions"],
      ["Cope","Top half of a sand mould"],
      ["Drag","Bottom half of a sand mould — sits on the moulding board during preparation"],
      ["Flask","Rigid box (wood or metal) containing and supporting the cope and drag halves"],
      ["Parting line","Interface where cope and drag meet — leaves a visible seam on the finished casting"],
      ["Pouring basin","Funnel at top of mould — receives molten metal smoothly, reduces turbulence and splash"],
      ["Sprue","Tapered vertical channel through which metal flows down into the mould. Tapered to prevent air ingestion."],
      ["Runner","Horizontal channel at base of sprue — distributes molten metal laterally to the gates"],
      ["Gate","Narrow entry point into mould cavity — controls flow rate and is easy to snap off after solidification"],
      ["Cavity","The hollow space within the mould that defines the final shape of the casting"],
      ["Core","Sand insert placed in cavity to create hollow internal features — also allows for shrinkage"],
      ["Chaplet","Metal support holding the core in correct position during pouring — must have higher melting point than cast metal"],
      ["Riser","Reservoir of molten metal that solidifies LAST — feeds liquid metal into cavity to compensate solidification shrinkage"],
      ["Gating system","Complete delivery network: pouring basin → sprue → runner → gate → cavity"],
      ["Continuity principle","Volume flow rate constant throughout gating system — governs why sprue must be tapered"],
      ["Strength (sand)","Sand mould holds shape and resists erosion when hot metal is poured"],
      ["Permeability (sand)","Allows hot gases and air to escape through voids between sand grains during pouring"],
      ["Thermal stability (sand)","Sand resists cracking on direct contact with molten metal — primary material: Silica SiO2"],
      ["Collapsibility (sand)","Sand gives way as casting shrinks during cooling — prevents hot tearing and aids removal"],
      ["Reusability (sand)","Sand from broken mould collected and reused for new moulds — reduces cost"],
      ["Refractory","Withstands high temperatures without degrading — key property of silica sand"],
      ["Green strength","Ability of compacted unbaked sand to hold shape during pattern removal and pouring"],
      ["Thermal arrest","Flat section on pure metal cooling curve — temperature constant while latent heat of fusion is released"],
      ["Latent heat of fusion","Energy released when liquid solidifies — compensates heat loss, causing thermal arrest in pure metals"],
      ["Liquidus (TL)","Temperature at which an alloy begins to solidify — above this it is fully liquid"],
      ["Solidus (TS)","Temperature at which an alloy is completely solid — below this no liquid remains"],
      ["Freezing range","Temperature range between TL and TS — alloys freeze gradually here, not at a single temperature"],
      ["Mushy zone","Semi-solid state within freezing range — part liquid, part solid. Prone to segregation and micro-porosity."],
      ["Segregation","Non-uniform composition in alloy casting — different elements freeze at different times"],
      ["Isotropic","Properties same in all directions — equiaxed grains. Desirable for general engineering."],
      ["Anisotropic","Properties differ with direction — columnar grains, also deliberate in composites"],
      ["Chill zone","Thin outermost layer at mould wall — very fine, randomly oriented grains from rapid cooling"],
      ["Columnar zone","Long grains growing inward opposite to heat flow direction — anisotropic"],
      ["Equiaxed zone","Centre grains — equal size in all directions, isotropic, best mechanical properties"],
      ["Fine grains","Result of rapid cooling — stronger and tougher at room temperature (more grain boundaries)"],
      ["Coarse grains","Result of slow cooling — weaker at room temp, better creep resistance at high temperatures"],
      ["3 shrinkage stages","1) Liquid contraction 2) Solidification shrinkage (largest — riser feeds this) 3) Solid thermal contraction"],
      ["Directional solidification","Regions furthest from riser freeze first — ensures continuous liquid metal supply to compensate shrinkage"],
      ["Chill (heat sink)","Internal or external metal insert causing rapid local freezing to control solidification direction"],
      ["Porosity","Voids from trapped gas or solidification shrinkage — weakens part. Caused by turbulent flow or poor riser."],
      ["Cold shut","Two metal flow fronts meet but don't fuse — premature freezing creates visible seam and stress concentration"],
      ["Misrun","Metal solidifies before completely filling cavity — metal too cold, poured too slow, or section too thin"],
      ["Cold shots","Metal splatters during pouring — solid globules become entrapped in casting body"],
      ["Hot tearing","Cracking from RIGID mould restricting thermal contraction — NOT flexible mould. Collapsibility prevents this."],
      ["Sand blow","Balloon-shaped gas cavity caused by release of mould gases during pouring"],
      ["Sand wash","Sand erosion during pouring — rough surface or sand particles embedded in casting surface"],
      ["Micro-porosity","Very fine voids distributed throughout casting — caused by solidification shrinkage in alloy mushy zone"],
      ["Investment casting","Lost wax process — wax pattern coated in ceramic slurry, wax melted out, metal poured into ceramic shell"],
      ["Lost wax","Wax pattern 'lost' (melted out) before metal poured — wax CAN be recovered and reused"],
      ["Wax tree","Multiple wax patterns attached to central wax sprue — all cast simultaneously for efficiency"],
      ["Ceramic shell","Thin precision ceramic mould built by repeated dipping — smooth surface, high accuracy"],
      ["EPS / Lost foam","Polystyrene pattern vaporised by incoming molten metal — no pattern removal needed. Can still have core shift defects."],
      ["Die casting","Molten metal injected under high pressure into permanent metal die — fast, excellent dimensional accuracy"],
      ["Hot chamber die casting","Injection mechanism submerged in melt — fast, continuous cycle. Zinc and tin alloys ONLY."],
      ["Cold chamber die casting","Injection mechanism separate from melt — metal ladled in per shot. For reactive metals: Al, Mg, Cu."],
      ["Ejector pins","Push solidified casting out of die at end of each cycle — leave small witness marks on casting"],
      ["Thermal fatigue","Die cracking from repeated heating and cooling cycles — limits service life of permanent moulds"],
      ["Centrifugal casting","Spinning mould flings metal outward against walls — hollow centre forms naturally, no core needed"],
      ["Axisymmetric","Symmetrical about a central axis — the only geometry centrifugal casting can produce"],
      ["Chvorinov's rule","Ts = C × (V/A)² — solidification time proportional to square of volume-to-surface-area ratio"],
      ["Mould constant (C)","Combines mould material, metal type and temperature — always given in exam questions"],
      ["Sprue velocity","v = √(2gh) — velocity at base of sprue. g = 981 cm/s², h = sprue height in cm."],
      ["Volume flow rate","Q = v × A — flow rate through sprue base. A = cross-sectional area at base."],
      ["Mould fill time","T = V/Q — time to fill cavity. V = cavity volume, Q = volumetric flow rate."],
      ["Die casting production rate","3600 / Tc parts per hour — where Tc is cycle time in seconds"],
      ["Induction furnace","AC current through coil creates magnetic field — rapid heating and melting of metal"],
      ["Cupola furnace","Vertical shaft furnace for ferrous metals (iron) — NOT suitable for non-ferrous metals"],
      ["Crucible furnace","Non-ferrous metals melted in ceramic crucible — flexible, used for Al, Cu, Mg"],
      ["Semi-solid casting","Metal processed in mushy zone — spheroidal microstructure, better tolerance than die casting"],
    ]
  },
  t3: {
    name: "Topic 3 — Plastics Shaping",
    terms: [
      ["Thermoplastic (TP)","Re-meltable and recyclable — chemical structure unchanged during heating and shaping. Like butter."],
      ["Thermoset (TS)","Permanently cured by heat — irreversible cross-linked network. Cannot be remelted. Like concrete."],
      ["Curing","Chemical cross-linking of thermoset molecules during heating — MOST time-consuming step in TS cycle"],
      ["Cross-linking","Chemical bonds formed between polymer chains — makes thermosets permanent and elastomers elastic"],
      ["Viscosity","Resistance to flow — higher molecular weight = higher viscosity, higher temperature = lower viscosity"],
      ["Shear rate","Rate at which fluid layers slide past each other — higher shear rate reduces viscosity in shear-thinning fluids"],
      ["Shear thinning","Viscosity decreases as shear rate increases — polymer melts flow easier when pushed harder. Non-Newtonian."],
      ["Pseudoplastic fluid","Another term for shear-thinning fluid — viscosity depends on shear rate. All polymer melts are pseudoplastic."],
      ["Newtonian fluid","Viscosity constant regardless of shear rate — water, oil. Opposite of polymer melt behaviour."],
      ["Viscoelasticity","Combined viscous and elastic behaviour — polymer chains have memory of their natural coiled state"],
      ["Die swell","Extrudate swells larger than die opening on exit — chains relax from stretched to coiled state"],
      ["Elastic recovery","Chains returning to natural coiled state after stretching — cause of die swell and springback"],
      ["Molecular weight","Mass of a polymer chain — longer chains = higher viscosity = harder to process"],
      ["Extruder barrel","Cylindrical heated tube — contains screw, melts pellets by friction and conduction"],
      ["Extruder screw","Rotates inside barrel — conveys solid pellets, melts them, builds pressure toward the die"],
      ["Hopper","Feed funnel at inlet of extruder — holds plastic pellets and feeds them into barrel continuously"],
      ["Screen pack","Wire mesh filter before die — removes contaminants, builds back-pressure, straightens rotating melt flow"],
      ["Die (extrusion)","Separate, replaceable shaping tool — NOT part of extruder. Each cross-section needs its own die."],
      ["Mandrel","Pin held in centre of extrusion die by spider legs — creates hollow profiles (pipes, tubes)"],
      ["Spider legs","Streamlined supports holding mandrel in die centre — polymer flows around them and rejoins"],
      ["L/D ratio","Length to diameter ratio of extruder barrel — shorter for rubber (10-15) to prevent premature vulcanisation"],
      ["Drag flow (Qd)","Forward polymer flow created by rotating screw pushing melt toward the die"],
      ["Back pressure flow (Qb)","Reverse flow caused by die resistance pushing melt backward against screw"],
      ["Net flow (Qx)","Qx = Qd - Qb — actual output volumetric flow rate from extruder"],
      ["Spinneret","Multi-hole extrusion die — produces many continuous fibres or filaments simultaneously"],
      ["Filament","Continuous fibre of very small diameter — at least 100× longer than its cross-sectional diameter"],
      ["Melt spinning","Polymer melted, extruded through spinneret, wound — most common fibre spinning method"],
      ["Frost line","Height at which blown film polymer solidifies — higher frost line = more stretching = thinner film"],
      ["Gauge accuracy","Precision of sheet or film thickness — calendering offers very high gauge accuracy consistently"],
      ["Injection unit","Melts and delivers plastic into mould — contains barrel, screw, non-return valve. Does NOT hold mould."],
      ["Clamping unit","Holds two mould halves shut during injection — provides alignment and clamping force. NOT the injection unit."],
      ["Non-return valve","Prevents melt flowing back up screw channel during the high-pressure injection stroke"],
      ["Injection moulding cycle","Clamp → Inject → Solidify → Eject — four stages, always in this order"],
      ["Compaction time","Time screw holds pressure in mould after injection — longer time = less shrinkage (more material packed in)"],
      ["Shrinkage (injection)","Cavity must be oversized — reduced by: higher pressure, longer compaction, higher temp, fillers. Increased by: thicker parts."],
      ["Charge","Measured amount of raw material loaded into mould before pressing — must be precisely controlled"],
      ["Compression moulding","Thermosets mainly — charge placed in heated mould, pressed, cured, ejected. Min 1,000 parts."],
      ["Transfer moulding","Thermosets — charge in separate pot, forced through channels into cavity. Better for complex shapes and inserts."],
      ["Parison","Soft plastic tube used as starting form in blow moulding — inflated with air to take mould shape"],
      ["Blow moulding","TP ONLY — parison inflated with air inside closed mould. Three variants: extrusion, injection, stretch blow."],
      ["Rotational moulding","Gravity coats inside of slowly rotating heated mould — large hollow parts. TP and TS both possible."],
      ["Thermoforming","TP ONLY — solid sheet heated and pressed or vacuumed into mould shape. Cannot be done with thermosets."],
      ["Negative mould (thermo)","Concave cavity — sheet drawn into depression by vacuum. Inside of part contacts mould."],
      ["Positive mould (thermo)","Convex raised form — sheet draped over and pressed down. Outside of part contacts mould."],
      ["RIM","Reaction injection moulding — two reactive liquid components mixed and injected into mould, cure in place"],
      ["RRIM","Reinforced RIM — glass fibres added to RIM reactive mixture. Automotive bumpers and body panels."],
      ["SMC","Sheet moulding compound — flat sheet of resin with 20-50% chopped glass fibre. Compression moulding."],
      ["BMC","Bulk moulding compound — dough-like compound with short fibres, better flow. Injection or compression moulding."],
    ]
  },
  t4: {
    name: "Topic 4 — Rubber & PMC",
    terms: [
      ["Elastomer","Polymer with very large reversible elastic deformation — light cross-links, Tg below room temperature"],
      ["Entropy-driven elasticity","Stretched chains spontaneously recoil to disordered state when released — thermodynamically driven by entropy increase"],
      ["Entropy","Measure of disorder in a system — nature tends toward higher entropy (more disordered states)"],
      ["Glass transition temp (Tg)","Temperature below which polymer chains become immobile → material becomes glassy and brittle"],
      ["Cross-link density","Number of chemical bonds between polymer chains — low = soft rubber, high = hard ebonite"],
      ["Polyisoprene","Natural rubber polymer — chemical formula (C5H8)n, long flexible chains with double bonds"],
      ["Hevea brasiliensis","Rubber tree — source of natural rubber latex, originally from Amazon, now grown in SE Asia"],
      ["Latex","Milky colloidal suspension of polyisoprene in water (~30% rubber) — tapped from Hevea brasiliensis trees"],
      ["Coagulation","Adding formic acid to latex — rubber particles clump and solidify into raw rubber sheet"],
      ["Pale crepe","Highest grade of natural rubber — lightest colour, best quality, most consistent"],
      ["RSS (Ribbed Smoked Sheet)","Standard natural rubber grade — dried in smokehouse, lower quality than pale crepe"],
      ["Compounding (rubber)","Adding additives to rubber — sulphur, carbon black, fillers, accelerators, plasticisers, antioxidants"],
      ["Masterbatch","Stage 1 mixing — all additives EXCEPT vulcanising agents. Must cool before adding sulphur."],
      ["Two-roll mill","Open rubber mixing machine — two counter-rotating rollers shear and fold rubber to disperse additives"],
      ["Banbury mixer","Enclosed internal mixer with counter-rotating rotors — more intensive mixing than two-roll mill"],
      ["Vulcanisation","Sulphur cross-linking of rubber chains by heating — discovered by Goodyear 1839. Modern: 15-20 min."],
      ["Sulphur bridges","Cross-links formed between polymer chains during vulcanisation — responsible for elastic recovery"],
      ["Accelerators (rubber)","ZnO + stearic acid — catalyse vulcanisation, reducing time from hours (Goodyear) to 15-20 minutes"],
      ["Carbon black","Primary reinforcing filler — colloidal carbon from hydrocarbon combustion. Strengthens + provides UV protection."],
      ["China clay","Non-reinforcing filler (hydrous aluminium silicate) — used when product cannot be black"],
      ["Reinforcing filler","Improves mechanical properties — carbon black is primary example. Increases tensile strength and modulus."],
      ["Ebonite","Hard rubber from very high cross-link density — bowling balls, hard protective cases, electrical insulation"],
      ["TPE","Thermoplastic elastomer — behaves like rubber in service, processes like thermoplastic. Recyclable, no vulcanisation needed."],
      ["PMC","Polymer matrix composite — polymer matrix (binds) + fibre reinforcement (provides strength). Intentionally anisotropic."],
      ["Matrix (PMC)","Polymer component of composite — binds fibres together, transfers load to fibres, protects fibres"],
      ["Reinforcement (PMC)","Fibre component of composite — carries structural load. Glass, carbon, or aramid."],
      ["Prepreg","Pre-impregnated reinforcement — resin already in fibre before lay-up. Higher control, stored frozen, higher cost."],
      ["Glass fibre","Low cost, good stiffness reinforcement — fibreglass boats, wind turbine blades, car panels"],
      ["Carbon fibre (CFRP)","High stiffness and strength, lightweight — aerospace, F1 cars, premium sports equipment. Expensive."],
      ["Aramid (Kevlar)","High toughness and impact energy absorption — bulletproof vests, helmets, cut-resistant gloves"],
      ["Continuous fibres","Full-length fibres — highest structural performance. CANNOT flow into complex mould shapes."],
      ["Chopped fibres","Short random fibres — moderate performance. CAN flow into complex shapes (SMC, BMC, spray-up)."],
      ["Open mould (PMC)","Low tooling cost process — hand lay-up, spray-up, filament winding. Labour intensive, low production rate."],
      ["Closed mould (PMC)","Higher tooling cost — compression, transfer, injection moulding of SMC/BMC. Higher production rate."],
      ["Hand lay-up","Manual application of resin and fibre layers onto open mould — gel coat first, rolled to remove air"],
      ["Spray-up","Simultaneous spray of resin and chopped fibres onto open mould — faster than hand lay-up, lower properties"],
      ["Automated tape laying","CNC gantry lays prepreg tape in programmed paths — aerospace wing skins, high repeatability"],
      ["Gel coat","First layer applied in hand lay-up — gives surface appearance and protects underlying fibres from environment"],
      ["Filament winding","Continuous fibres wound onto rotating mandrel through resin bath — pressure vessels, LPG cylinders, pipes"],
      ["Winding angle","Angle of fibre path in filament winding — controls balance of hoop vs axial strength"],
      ["Hoop strength","Resistance to circumferential (bursting) stress — maximised by filament winding at ~90° to axis"],
      ["Pultrusion","Fibres pulled through resin bath then heated die — constant cross-section profiles only (beams, rails)"],
      ["Pulforming","Modified pultrusion — allows curved profiles and variable cross-section"],
    ]
  },
  t5: {
    name: "Topic 5 — Powder Metallurgy",
    terms: [
      ["Powder metallurgy (PM)","Manufacturing from metal powder — Powder → Compaction → Sintering. No melting required."],
      ["Green compact","Part after compaction — particles mechanically interlocked. Weak, porous, handleable. NOT sintered."],
      ["Sintering","Heating compacted powder to 70-90% of Tm — atomic diffusion bonds particles without melting. 1-5% shrinkage."],
      ["Neck formation","Stage 1 sintering — atoms diffuse across particle boundaries forming small bonding necks"],
      ["Pore shrinkage","Stage 2 sintering — necks grow larger, pores become smaller and more rounded"],
      ["Grain growth","Stage 3 sintering — little further densification, grain boundaries migrate and grains enlarge"],
      ["Gas atomisation","Inert gas jet breaks molten metal into droplets — spherical particles, excellent flowability, aerospace quality"],
      ["Water atomisation","High-pressure water jet breaks molten metal — irregular particles, better compaction, cheaper than gas"],
      ["Chemical reduction","Metal oxide chemically reduced to metal powder — very fine, high purity. Tungsten, iron, nickel."],
      ["Electrolysis (PM)","Metal dissolves from anode, deposits as powder at CATHODE — very high purity. Copper, iron."],
      ["Spherical particles","From gas atomisation — flow easily into die, fill complex shapes, less compact than irregular"],
      ["Irregular particles","From water atomisation — mechanical interlocking gives better green compact strength"],
      ["Elemental powder","Each particle is a pure metal — mixed to form alloys during sintering"],
      ["Pre-alloyed powder","Each particle already has final alloy composition — used for stainless steels, superalloys"],
      ["Packing factor","Bulk density / True density — typically 0.5-0.7. Mixed particle sizes improve packing significantly."],
      ["Angle of repose","Angle of powder heap when poured — lower angle = better flowability. Spherical → low angle."],
      ["Blending","Combining powders of SAME composition but different sizes — improves packing density"],
      ["Mixing","Combining powders of DIFFERENT compositions — creates alloy precursors. Fe + graphite = mixing, not blending."],
      ["Compaction","Pressing powder into die under high pressure — particles rearrange, interlock, green compact formed"],
      ["Compaction force","F = Ap × Pc — Ap = projected area (mm²), Pc = pressure (MPa = N/mm²), F in Newtons"],
      ["Press capacity","Maximum force a press can apply — larger parts and higher compaction pressures need bigger presses"],
      ["Density gradient","Non-uniform density in conventionally compacted parts — higher near punches, lower in middle"],
      ["Sizing","Light repressing after sintering — corrects 1-5% shrinkage, improves dimensional accuracy and roundness"],
      ["Coining","Heavy repressing after sintering — densifies surface regions, improves surface finish and contact strength"],
      ["Infiltration","Lower-melting metal (bronze) placed on sintered part, heated, wicks into pores by capillary action"],
      ["Impregnation","Oil fills pores of sintered part — creates self-lubricating bearings (no external lubrication needed)"],
      ["Self-lubricating bearing","PM bearing with oil in pores — rotation generates heat, oil seeps out and lubricates automatically"],
      ["HIP (Hot Isostatic Pressing)","Inert gas pressure from all directions at high temp — eliminates porosity, near full theoretical density"],
      ["CIP (Cold Isostatic Pressing)","Water pressure from all directions at room temp — uniform density without heat"],
      ["MIM (Metal Injection Moulding)","Powder + polymer binder injection moulded, binder removed, sintered — complex small high-volume parts"],
      ["Debinding","Removing polymer binder from MIM green part — thermal (burnout) or solvent debinding before sintering"],
      ["Mesh count (Mc)","Number of openings per linear inch on mesh screen — higher Mc = finer mesh = smaller particles pass through"],
      ["Particle size formula","Size = (25.4/Mc) − wire diameter (mm). 25.4 mm = 1 inch."],
      ["Controlled porosity","Deliberately leaving pores in PM part — up to 50% possible. Essential for bearings."],
      ["Sintering atmosphere","H₂ (reducing), Ar (inert), N₂ (protective), or vacuum — prevents oxidation of powder during sintering"],
      ["Spark sintering","Punches act as electrodes — electrical discharge generates rapid localised heating at contact points"],
      ["Liquid phase sintering","One component melts during sintering — liquid fills gaps and promotes faster densification. WC-Co."],
    ]
  },
  t6: {
    name: "Topic 6 — Metal Forming",
    terms: [
      ["Plastic deformation","Permanent shape change — occurs when applied stress exceeds yield strength. No material removed."],
      ["Elastic deformation","Temporary shape change — recovers completely when force removed. Below yield strength."],
      ["Yield strength","Stress at which plastic deformation begins — transition from elastic to plastic regime"],
      ["Dislocation","Line defect in crystal lattice — allows plastic deformation via slip. Density increases with plastic strain."],
      ["Work hardening","Dislocation density increases during plastic deformation — strength ↑, ductility ↓. Also called strain hardening."],
      ["Recrystallisation","New strain-free grains nucleate at ~0.5 Tm — removes work hardening, restores ductility"],
      ["Flow stress (σ)","Instantaneous stress required to continue plastic deformation at a given strain — increases with strain"],
      ["Average flow stress (Ȳf)","Representative stress over a forming operation — Ȳf = Kεfⁿ / (1+n) = flow stress / (1+n)"],
      ["Hollomon equation","σ = Kεⁿ — flow curve relating stress to strain. K = strength coefficient, n = strain hardening exponent."],
      ["Strength coefficient (K)","Material constant in Hollomon equation — equals flow stress at true strain = 1.0"],
      ["Strain hardening exponent (n)","How strongly material work hardens — high n = strong hardening, low n = little hardening"],
      ["True strain","Natural log of dimensional change ratio — used in flow curve calculations"],
      ["Cold working","Below 0.3 Tm — high forces needed, excellent dimensional accuracy, significant work hardening"],
      ["Warm working","0.3-0.5 Tm — intermediate forces, some work hardening, extra heat required"],
      ["Hot working","Above recrystallisation temp (~0.5 Tm) — low forces, no work hardening (recrystallises), surface oxidation"],
      ["Rolling","Most widely used bulk forming — metal passed between rotating rolls reducing thickness"],
      ["Flat rolling","Flat rolls reduce rectangular cross-section — plates, sheets, coils"],
      ["Shape rolling","Shaped groove rolls produce structural profiles — I-beams, H-beams, railway rails, channels"],
      ["Thread rolling","Cold rolling threads onto fasteners — stronger than cut threads, better fatigue resistance, no waste"],
      ["Ring rolling","Thick small ring rolled into thin large ring — hot for large rings, cold for small rings"],
      ["Open-die forging","Metal compressed between flat dies and flows freely — simple shapes, large parts, artistic work"],
      ["Impression-die forging","Shaped die cavity forms complex parts — crankshafts, connecting rods. Flash helps fill cavity."],
      ["Flash (forging)","Thin excess metal squeezed out between dies — friction resists flow, forces metal into every cavity corner"],
      ["Flash trimming","Removing flash after forging — separate shearing operation, usually done while still hot"],
      ["Flashless forging","Precision forging — no flash, no waste, billet volume must exactly match die cavity volume"],
      ["Upset forging","Most common forging op — axial compression shortens and widens workpiece. Bolt heads, nails, rivets."],
      ["Header / former","Machine for upset forging — cold, warm or hot. Makes fastener heads."],
      ["Direct extrusion","Ram pushes billet toward fixed die — metal flows same direction as ram. Most common method."],
      ["Indirect extrusion","Die moves toward stationary billet — metal flows backward through hollow ram. Lower friction."],
      ["Billet (forming)","Starting solid cylindrical workpiece for extrusion or forging — heated for warm/hot working"],
      ["Wire/bar drawing","Metal pulled through converging die by tensile force — cold working reduces cross-section"],
      ["Sheet metalworking","Forming operations on thin sheet (0.4-6mm) using presses — products called stampings"],
      ["Punch (sheet)","Convex tool that presses or cuts sheet metal — moves downward into or through the workpiece"],
      ["Die (sheet)","Shaped opening or cavity that sheet metal is pressed into — stationary member"],
      ["Stamping","Finished sheet metal product from pressworking operations"],
      ["Shearing","Cutting sheet metal along a straight line between opposing blades"],
      ["Blanking","Cut piece IS the desired part — surrounding stock is scrap. Used for coins, washers, discs."],
      ["Punching","Cut piece (slug) IS the scrap — surrounding stock with hole is the desired part"],
      ["Slug","Scrap piece removed from sheet during punching — discarded"],
      ["Clearance (cutting)","Gap between punch and die — typically 4-8% of sheet thickness. Affects cut quality."],
      ["4 cutting stages","1) Contact — punch touches sheet 2) Plastic deformation 3) Penetration — clean cut zone 4) Fracture"],
      ["V-bending","Sheet pressed into V-shaped die by V-shaped punch — simple, low tooling cost, low production"],
      ["Edge bending","Sheet clamped by pressure pad, punch bends it over die edge — complex tooling, high production"],
      ["Springback","Elastic recovery after bending causes angle to open — fixed by overbending past desired angle"],
      ["Deep drawing","Punch draws flat blank into die cavity to form hollow cup — cans, car panels, kitchen sinks"],
      ["Blank (drawing)","Flat circular starting sheet for deep drawing — diameter determines material available for cup"],
      ["Blankholder","Clamps outer edges of blank during drawing — essential to prevent wrinkling of flange"],
      ["Wrinkling (drawing)","Flange buckling under compressive stress during drawing — prevented by blankholder"],
      ["Tearing (drawing)","Wall fracture at punch radius — caused by excessive tensile stress or sharp punch corner"],
      ["Earing (drawing)","Uneven scalloped rim on drawn cup — caused by anisotropy in starting sheet material"],
      ["Redrawing","Multi-stage drawing to achieve deep cups — each stage reduces diameter and increases depth"],
      ["Ironing","Cup wall forced through narrow die gap — thins and elongates walls uniformly. Drinks cans."],
      ["Embossing","Creates raised or indented shallow features in sheet — lettering, ribs, decorative patterns"],
      ["Barrelling","Bulging at mid-height during open-die forging due to friction — non-uniform deformation"],
      ["Grain flow","Directional grain alignment during forming — improves strength in flow direction vs machined equivalent"],
    ]
  },
  t7: {
    name: "Topic 7 — Metal Machining",
    terms: [
      ["Machining","Material removal from solid workpiece to achieve desired geometry — subtractive manufacturing"],
      ["Turning","Workpiece rotates, single-point tool moves linearly — machine: lathe. Produces external cylindrical surfaces."],
      ["Milling","Multi-point rotary cutter, workpiece moves — machine: milling machine. Flat surfaces, slots, profiles."],
      ["Drilling","Rotary tool advances into stationary workpiece — machine: drill press. Creates round holes only."],
      ["Boring","Enlarges existing hole from inside — effectively internal turning. Often on drill press or milling machine."],
      ["Broaching","Multi-tooth tool moved linearly in one pass — each tooth cuts progressively deeper. Non-circular holes, keyways."],
      ["Shaping","Single-point tool moves back and forth across stationary workpiece — produces flat surfaces"],
      ["Planing","Workpiece moves back and forth past stationary tool — produces flat surfaces. Opposite of shaping."],
      ["Facing","Turning operation producing flat surface on end of rotating workpiece"],
      ["Taper turning","Tool fed at controlled angle to produce conical surface on workpiece"],
      ["Threading (external)","Cuts helical external thread on cylindrical surface — the bolt side"],
      ["Tapping","Cuts helical internal threads into existing hole — the nut side"],
      ["Through hole","Drill exits completely through opposite side of workpiece"],
      ["Blind hole","Drill does NOT exit opposite side — flat or conical bottom, specific depth"],
      ["Counterboring","Creates stepped hole with flat bottom to seat bolt head flush below surface"],
      ["Countersinking","Creates conical stepped hole for flat-headed screws to sit flush"],
      ["Centering","Drills a starting cone to guide subsequent drill bits precisely"],
      ["Reaming","Precision sizing of existing hole — removes small amount of material for accurate diameter"],
      ["Peripheral milling","Cutter axis parallel to workpiece surface — cutting on outside of cutter"],
      ["Face milling","Cutter axis perpendicular to workpiece surface — cutting on end and edge of cutter"],
      ["Cutting speed (v)","Relative speed of cutting edge past workpiece surface — primary cutting motion"],
      ["Feed (f)","Distance tool advances per revolution — secondary motion. High feed = rougher surface."],
      ["Depth of cut (d)","Depth tool penetrates below workpiece surface — affects chip thickness and cutting force"],
      ["MRR (Material Removal Rate)","MRR = v × f × d — rate of material removal. Higher MRR = more aggressive cut."],
      ["Roughing cuts","High feed and depth, low speed — removes large amounts of material quickly, poor surface"],
      ["Finishing cuts","Low feed and depth, high speed — achieves final dimensions, good surface finish"],
      ["Chip thickness ratio (r)","r = to/tc — always less than 1.0 (chip is thicker than original layer). Indicates cutting conditions."],
      ["Rake angle","Angle of tool face relative to perpendicular — positive rake: easier cut, negative rake: more friction"],
      ["Clearance angle","Tool angle preventing rubbing of flank against machined surface"],
      ["Shear angle (φ)","Controls chip formation geometry — determines chip thickness, cutting forces"],
      ["Continuous chip","Ductile material, high speed, sharp tool, small feeds — BEST surface finish. Long ribbon."],
      ["Discontinuous chip","Brittle material, low speed, large feeds — chip breaks into segments"],
      ["BUE (Built-Up Edge)","Ductile material, low-medium speed — chip welds to rake face, grows, breaks off cyclically. Damages finish."],
      ["Serrated chip","Difficult-to-machine metals at high speed — alternating shear zones, saw-tooth appearance"],
      ["Ideal surface roughness (Ri)","Ri = f²/(8×NR) — theoretical best surface roughness. Lower feed and larger nose radius = smoother."],
      ["Chatter","Tool/workpiece vibration — creates wavy rippled surface. Fixed by increasing stiffness, reducing feeds."],
      ["Single-point tool","One dominant cutting edge — turning tools. Can be resharpened. Insert type common."],
      ["Multi-point tool","More than one cutting edge — drills and milling cutters. Rotation provides cutting speed."],
      ["Tool nose radius (NR)","Rounded tip of cutting tool — larger NR = smoother surface finish but more radial force"],
    ]
  },
  t89: {
    name: "Topics 8 and 9 — Cutting Tools and Grinding",
    terms: [
      ["Tool life","Time or volume of material removed before tool replacement needed — defined by flank wear criterion"],
      ["Tool life criterion","Replace tool at 0.5mm flank wear — industry standard for most operations"],
      ["Fracture failure","Sudden tool breakage — most dangerous failure mode. Unpredictable, can damage workpiece."],
      ["Temperature failure","Excessive heat softens cutting edge — loses geometry and cutting ability"],
      ["Gradual wear","Slow progressive wear — preferred failure mode. Predictable, allows planned replacement."],
      ["Crater wear","Depression worn into rake face where chip slides over tool — chip acts as abrasive"],
      ["Flank wear","Flat worn area on flank face rubbing against machined surface — measured in mm, replace at 0.5mm"],
      ["Taylor tool life equation","vTⁿ = C — higher speed = shorter tool life, non-linear relationship"],
      ["Taylor exponent (n)","Material and tool constant — steeper curve (lower n) = tool life drops faster with speed"],
      ["Hot hardness","Ability to maintain hardness at elevated temperatures — critical property for cutting tools"],
      ["HSS (High Speed Steel)","Maintains hardness to ~600°C — drills, taps, reamers, milling cutters. Resharpenable."],
      ["Cemented carbides","WC + Co binder — harder and more heat resistant than HSS. Higher cutting speeds."],
      ["Coated carbides","Cemented carbide + TiC/TiN/Al₂O₃ coating (2.5-13μm) — applied by CVD or PVD. Longer life."],
      ["CVD (Chemical Vapour Deposition)","Coating process — hot chemical vapour deposits thin hard ceramic layer on carbide insert"],
      ["PVD (Physical Vapour Deposition)","Coating process — lower temperature than CVD, used when sharp cutting edges needed"],
      ["Cermets","Ceramic-metal composite tool material — between carbides and ceramics in performance"],
      ["Ceramics (cutting)","Very high hardness and heat resistance — brittle, not for interrupted cuts or heavy feeds"],
      ["CBN (Cubic Boron Nitride)","Second hardest material — for hardened steels and superalloys. Does not react with iron."],
      ["Synthetic diamond","Hardest material — for non-ferrous metals, ceramics, composites. CANNOT be used on steel."],
      ["Diamond-iron reaction","Diamond (carbon) reacts chemically with iron at machining temperatures — tool dissolves. Use CBN for steel."],
      ["Coolant-type cutting fluid","Water-based — primary function is heat removal. Best at high cutting speeds."],
      ["Lubricant-type cutting fluid","Oil-based — primary function is friction reduction at tool interfaces. Best at low cutting speeds."],
      ["Dry machining","No cutting fluid — avoids contamination, requires lower speeds and carefully selected tool materials"],
      ["Production cycle time (Tc)","Tc = Th + To + Tt — total time per part including handling, machining, tool change"],
      ["Handling time (Th)","Time to load and unload workpiece — non-cutting time that affects cost"],
      ["Machining time (To)","Actual time spent cutting — reduced by higher cutting speed but increases tool wear"],
      ["Tool change time (Tt)","Time per part attributed to tool changes — depends on how often tool is replaced"],
      ["Cost per part (Cpc)","Cpc = Cm + (CL+Ceq)Tc + Ct — total cost including material, labour, equipment, tooling"],
      ["Insert (cutting tool)","Replaceable cutting tip clamped in toolholder — various shapes. Indexable: rotate to fresh edge."],
      ["Grinding","Abrasive machining — material removed by hard random abrasive grains at very high speeds"],
      ["Abrasive grain","Hard cutting particle in grinding wheel — Al₂O₃, SiC, CBN, or diamond"],
      ["Bond material","Holds abrasive grains together in wheel — vitrified, resinoid, rubber, or metal bond"],
      ["Porosity (grinding wheel)","Spaces between abrasive grains — chip clearance, coolant access, prevents clogging"],
      ["Friability","Ability of abrasive grains to fracture and expose new sharp edges — self-sharpening property"],
      ["Glazing","Wheel surface becomes smooth from dull, unbroken grains — wheel stops cutting, generates heat"],
      ["Wheel grade","Strength of bond holding grains — hard = grains stay, soft = grains released easily"],
      ["Wheel structure","Grain spacing — dense = more cutting edges + better finish, open = more chip space + higher MRR"],
      ["Hard workpiece → soft grade","Hard material dulls grains fast — need soft bond to release dull grains and expose fresh ones"],
      ["Dressing","Sharpening grinding wheel — removes dull grains to expose fresh sharp cutting points"],
      ["Truing","Reshaping grinding wheel — restores concentricity and geometry after irregular wear"],
      ["Grain action — cutting","Abrasive grain actually removes material — only a fraction of all grains do this"],
      ["Grain action — ploughing","Grain deforms surface but does not remove material — creates sub-surface damage"],
      ["Grain action — rubbing","Grain slides without cutting — pure friction and heat generation, no material removal"],
      ["Honing","Abrasive sticks with rotational + oscillating motion — cross-hatch pattern retains oil. Engine cylinders."],
      ["Superfinishing","Fine abrasive stone with very light oscillating pressure — very smooth surface. Bearings, shafts."],
      ["Lapping","Abrasive slurry between mating surfaces — highest accuracy achievable. Optics, gauges."],
      ["Precision order","Grinding → Honing → Superfinishing → Lapping (increasing precision, decreasing material removal)"],
    ]
  },
  t10: {
    name: "Topic 10 — Heat Treatment, AM & SSM",
    terms: [
      ["Heat treatment","Heating and cooling process causing both microstructural AND mechanical property changes"],
      ["Annealing","Heat below Tm, soak, SLOW cool — softens metal, improves ductility, relieves residual stresses"],
      ["Stress-relief annealing","Low-temperature anneal to remove residual stresses from forming/welding without changing microstructure"],
      ["Recrystallisation annealing","Anneal at recrystallisation temp to restore ductility of cold-worked material"],
      ["Hardening (quench)","Heat steel above critical temp to form austenite, then rapidly quench — produces martensite"],
      ["Tempering","Heat previously hardened steel to intermediate temp — REDUCES brittleness, NOT increases hardness"],
      ["Quenching","Rapid cooling of metal — fastest to slowest: Brine > Agitated water > Still oil > Air"],
      ["Austenite","High-temperature FCC phase of steel — dissolves carbon easily, forms above ~723°C"],
      ["Martensite","Forms by rapid quenching of austenite — distorted BCC, carbon trapped. Very hard and brittle."],
      ["Pearlite","Forms by slow cooling of austenite — layered ferrite + cementite. MUCH SOFTER than martensite."],
      ["Bainite","Intermediate microstructure between pearlite and martensite — intermediate properties"],
      ["Critical temperature","~723°C for plain carbon steel — above this, austenite forms; below, ferrite/pearlite stable"],
      ["TTT diagram","Time-Temperature-Transformation — maps austenite transformation vs time and temperature for a specific steel"],
      ["Precipitation hardening","Solution treatment → quench → ageing. Fine precipitates block dislocation movement → hardening."],
      ["Solution treatment","Heat to HIGH temperature — all alloying elements dissolve into solid solution"],
      ["Quenching (PH)","Rapid cool from solution treatment — traps alloying elements in supersaturated solid solution"],
      ["Precipitation treatment","Heat to LOWER intermediate temperature — fine precipitates nucleate and grow → hardening"],
      ["Ageing","Alternative term for precipitation treatment — 'natural ageing' at room temp, 'artificial ageing' at elevated temp"],
      ["Nitriding","Introduces nitrogen into steel surface at elevated temp — nitride precipitates harden surface (precipitation mechanism)"],
      ["Surface hardening","Only hardens surface layer — carburising, nitriding, flame hardening. Core remains tough."],
      ["Additive manufacturing (AM)","Parts built layer-by-layer from CAD data — also called 3D printing or rapid prototyping"],
      ["Powder Bed Fusion (PBF)","Thin powder layer spread, laser selectively melts regions, platform lowers, repeat"],
      ["FDM (Fused Deposition Modelling)","Heated filament extruded from nozzle, deposited layer-by-layer — most common consumer 3D printing"],
      ["DED (Directed Energy Deposition)","Powder/wire fed into laser or electron beam melt pool — large parts, repair, feature addition"],
      ["Binder jetting","Liquid binder selectively deposited on powder bed — no melting during build, sintered afterwards"],
      ["Support structures (AM)","Required for overhanging features during AM build — NOT all AM parts are support-free"],
      ["AM porosity","Most common AM defect — gas entrapment, lack of fusion between layers, keyhole porosity"],
      ["AM distortion","Thermal gradients during build cause residual stresses and warping — managed by supports and build strategy"],
      ["AM surface roughness","Layer-by-layer staircase effect + partially melted powder — requires post-processing for smooth finish"],
      ["Columnar grains (AM)","Observed in many AM builds — directional heat flow during layer melting causes columnar growth"],
      ["Build direction","Influences surface finish and mechanical properties in AM — NOT limited to vertical only"],
      ["Powder degradation (AM)","Reused powder changes in particle size, satellite formation, oxidation — reduces consistency and quality"],
      ["SSM (Semi-Solid Metal) processing","Metal processed in mushy zone — thixotropic behaviour allows controlled flow of semi-solid slurry"],
      ["Thixotropy","At rest = solid-like. When sheared = liquid-like. Key behaviour enabling SSM processing."],
      ["Globular microstructure","Spheroidal grain structure required for SSM — formed by shearing during solidification"],
      ["Dendritic structure","Normal solidification microstructure (tree-branch pattern) — must be broken down to globular for SSM"],
      ["Rheo-route","SSM from liquid — cooled + sheared simultaneously. ONE step, no intermediate solidification. Lower cost."],
      ["Thixo-route","SSM from solid billet — reheat pre-processed billet. TWO steps with intermediate solidification. Higher control."],
      ["Thixomoulding","SSM for magnesium alloys — Mg chips heated in barrel with screw applying shear, injected into die"],
      ["Thixocasting","SSM at ~50% liquid fraction — more fluid behaviour, similar to high-pressure die casting"],
      ["Thixoforging","SSM at <50% liquid fraction — less fluid, higher pressure, closer to forging. Better properties."],
      ["SSM advantages","Lower porosity than HPDC, near-net shape, better dimensional tolerance, lower processing temperature"],
      ["Wide freezing range (SSM)","Alloys with wide TL-TS range preferred — larger processing window, easier to maintain mushy zone"],
    ]
  }
}
